Error: Verification failed in function 'test2'/'foo':
Function does not return 'void', so 'leave' is invalid.

The invalid instruction was (index 0 in block 'entry'):
leave
