Error: Verification failed in function 'test23'/'foo':
Tail calls can only be done in functions with standard calling convention.

The invalid instruction was (index 0 in block 'entry'):
invoke.tail ('test23'/'foo')
